# Generated by Django 3.0.2 on 2021-01-14 18:49

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourites',
            field=django_mysql.models.ListTextField(models.CharField(max_length=200), default=None, null=True, size=100),
        ),
    ]
